sudo: false
language: node_js
env: TEST_SUITE=unit
node_js:
  - "5.6.0"
cache:
  directories:
    - node_modules
install:
  - npm install
notifications:
  email: false

script: "npm run test:ci:$TEST_SUITE"
script: "npm run test:ci:functional"
